LABEL name="NAFWS" \
      author="David --> david.arteaga@globant --> Cybersec Studio" \
      description="Not A Fancy Web Service --> A simple python WS for security demos/testing" \
      version="1.0.1"
FROM ubuntu:latest

RUN apt update -y && apt install python3 python3-pip git -y

WORKDIR /home/
RUN git clone https://github.corp.globant.com/david-arteaga/NAFWS.git
RUN cd NAFWS

#RUN python3 -m pip install -r requierements.txt
#o
RUN pip3 install -r requierements.txt

#Caso 2.2
#RUN python3 -m pip install flask
#o
#RUN pip3 install flask

EXPOSE 5000

CMD ["python3","nafws.py"]